name: rampart-polio
channels:
  - bioconda
  - conda-forge
  - defaults
  # - jameshadfield
dependencies:
  - biopython=1.73
  - clint=0.5.1=py36_0
  - coreutils=8.25
  - mafft
  - medaka=0.10.0
  - miniasm
  - minimap2=2.17
  - nanopolish
  - pandas=0.23.0=py36_1
  - pip=19.1.1
  - python=3.6.6
  - racon=1.4.7
  # - rampart
  - samtools=1.9
  - snakemake=5.4.3
  - pip:
    - binlorry==0.1
    - h5py==2.7.1 
    - matplotlib==3.1.1
    - msgpack==0.5.6
    - nextstrain-augur
    - numpy==1.16.1
#    - git+https://github.com/artic-network/fieldbioinformatics.git
    - git+https://github.com/artic-network/Porechop.git
    - scipy==1.3.1
    - seaborn
    - tensorflow==1.14.0



