import os
from Bio import SeqIO

##### Configuration #####

barcodes = config["barcodes"].split(',')
barcode_string = ""
for i in barcodes:
    barcode_string+=" {}".format(i)

sample_string = ""
if config["sample"]:
    sample_string = config["sample"]
else:
    sample_string = "_".join(barcodes)
    config["sample"]=sample_string

# rounds = [1,2,3,4]
##### Target rules #####

rule all:
    input:
        expand(config["output_path"] + "/binned_{sample}/de_novo/draft_with_error.gfa",sample=config["sample"])

##### Modules #####

include: "rules/map_polish.smk",
include: "rules/unmapped.smk"
