##### Where is the data? #####

input_path: path/to/data
annotated_path: path/to/csv
output_path: path/to/binned #where rampart will put the binned/ filtered files 
config:  #this works but is a hack around needing to access this file within a python script

##### Mapping reference panel #####

references_file: references.fasta

##### Barcodes to process #####

sample:
barcodes: NBXX,NBYY

##### Read length filtering range #####

min_length: 500
max_length: 2500

##### Read thresholds #####

min_reads: 100
min_pcent: 5

##### Analysis Stem #####
